# Site settings
title: Notella
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Notes taken by Seikun Kambashi for various courses offered on Coursera and other similar sites.
baseurl: "/eUni" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: skambashi
github_username:  skambashi

# Build settings
markdown: kramdown
highlighter: pygments